spring:
  datasource:  #DB config
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tale?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
      username: tale
      password: 123456
      initial-size: 20
      min-idle: 10
      max-active: 100
  thymeleaf:  #模板配置
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
    cache: true   #这儿原来是false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.my.blog.website.dao
server:
  port: 8080
pagehelper:   #pagehelper
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql